options {
  directory "/var/cache/bind";
  version "not currently available";
  allow-query { any; };
  allow-query-cache { none; };
  recursion no;
};

zone "l2-3.ephec-ti.be." {
  type master;
  file "/var/cache/bind/l2-3.zone";
  allow-transfer {
    none;
  };
};
